### ISSUE TITLE
button to reload game 

### ISSUE THREAD

**Issue by Zakir2006** [Zakir2006/TetrisGame#1]
There is no option to restart the game, therefore we are going make a restart button to make it easy and fast to restart the game without having to click the reload button.

**Comment by cchho2** [comment]
<a href="https://striped-sapphire-primula.glitch.me">
      <button>Restart</button>
    </a>

**Comment by Zakir2006** [comment]
added:

/*<a href="https://striped-sapphi     re-primula.glitch.me">
  <button>Restart</button>
</a>
*/

we now have restart button for our game!\
Thank you Eric I love u so much
